name: data_volley_match
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_rich_text: ^2.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^6.0.0
  fluttertoast: ^8.2.4
  get_it: ^7.6.6
  google_sign_in: ^6.2.1
  image: ^4.1.4
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.2
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
