// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-hdQC64jvhN0RisVMppMfC91hmNTKjQs',
    appId: '1:273311948382:web:14dae59daa49530e579ecf',
    messagingSenderId: '273311948382',
    projectId: 'positiontaker-a126d',
    authDomain: 'positiontaker-a126d.firebaseapp.com',
    storageBucket: 'positiontaker-a126d.appspot.com',
    measurementId: 'G-MM6PPGBBT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuetonOEEHgep6q8PIORaj_1cZzIDdm9Y',
    appId: '1:273311948382:android:a1d6e7c36eaa46ea579ecf',
    messagingSenderId: '273311948382',
    projectId: 'positiontaker-a126d',
    storageBucket: 'positiontaker-a126d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwFoTZhAH6RfOsywHrrYXb-JrU4Zm9vk0',
    appId: '1:273311948382:ios:ef007aa8c25f65b0579ecf',
    messagingSenderId: '273311948382',
    projectId: 'positiontaker-a126d',
    storageBucket: 'positiontaker-a126d.appspot.com',
    iosBundleId: 'com.example.dataVolleyMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwFoTZhAH6RfOsywHrrYXb-JrU4Zm9vk0',
    appId: '1:273311948382:ios:6b0b4bd16f34323e579ecf',
    messagingSenderId: '273311948382',
    projectId: 'positiontaker-a126d',
    storageBucket: 'positiontaker-a126d.appspot.com',
    iosBundleId: 'com.example.dataVolleyMatch.RunnerTests',
  );
}
